---
title: "Logistic regression"
author: "Katlheen Sarmiento Fajardo"
date: "2024-06-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
####################################################
############ Regresión logística ###################
####################################################
#Transformamos a factores todas las variables que se utilizan en esta regresión
result_df$diab_prev <- as.factor(result_df$diab_prev)
result_df$PC1_tercile <- as.factor(result_df$PC1_tercile)
result_df$PC2_tercile <- as.factor(result_df$PC2_tercile)
result_df$PC3_tercile <- as.factor(result_df$PC3_tercile)
result_df$sexo <- as.factor(result_df$sexo)
result_df$colesterol<- as.factor(result_df$colesterol)

#Visualizamos en tablas la distribución y categorías de cada variable
table (result_df$PC1_tercile)
table (result_df$PC2_tercile)
table (result_df$PC3_tercile)
table (result_df$sexo)
table (result_df$colesterol)

#Corremos la función de regresión logística 
modelo_logistica <- glm(diab_prev ~ PC1_tercile + PC2_tercile + PC3_tercile + sexo + colesterol, data= result_df, family = "binomial")
summary(modelo_logistica)
confint(modelo_logistica) # calculamos el intervalo de confianza

exp(modelo_logistica$coefficients) # calculamos las OR
exp(coef(modelo_logistica)) # volvemos a calcular las OR
exp(confint(modelo_logistica)) # generamos el intervalo de confianza de las OR exponenciado

pseudo_R2_McFadden <- 1 - (modelo_logistica$deviance / modelo_logistica$null.deviance)
cat("Pseudo R-cuadrado de McFadden: ", pseudo_R2_McFadden, "\n")
```


